Mithminite scythe rework
Krutoy242/Enigmatica2Expert-Extended pull request #314
Opened 2023-11-26 19:25 UTC by TabakaSIM

Mithminite scythe reworked, that includes:
- all 51 aspects have effect!
- buffed projectiles
- augmentation mechanic
- questbook entry

> What was tested:
> - all effects
> - most "performance heavy" combination: aer, fluctus, vacuos, draco, rattus, mana, sonus, exitium

> What wasn't tested:
> - on server - i can't join on my local server :(

> What is missing:
> - translations .ru and .zh
> - gif with cool looking projectile effect (i'll add it later)

2023-11-26 19:27 UTC, Krutoy242 commented
Thank you for the contribution! I will take closer look later.

2023-11-26 19:37 UTC, Krutoy242 commented
Did you tested if scythe will keep it's enchants or other nbt tags like Random Tweaker anchor on upgrading?

2023-11-26 19:40 UTC, Krutoy242 commented
Maybe I got this wrong, but, is scythe storing it's upgrades worth lore nbt? As I recall, Random Tweaker have special lore tags that could change lore of items. Did you test if it would exploit or destroy your nbt?

2023-11-26 19:44 UTC, Krutoy242 commented
Please move crafting hints to scythe zs file. I did a mistake by adding modded hints to hints.zs file itself and want to keep it as library that other files using. I will need to refactor that later but for now you could just nice each hint to respective mechanic function definition.

2023-11-26 20:28 UTC, Krutoy242 commented
Ok, since I don't know other way to unhide this comments I will show them as images 😅


![Screenshot_2023-11-26-23-27-44-431_com.github.android.jpg](https://github.com/Krutoy242/Enigmatica2Expert-Extended/assets/936618/d1030834-7a51-40d8-bdbb-cc7bad868821)

![Screenshot_2023-11-26-23-27-41-495_com.github.android.jpg](https://github.com/Krutoy242/Enigmatica2Expert-Extended/assets/936618/9f275d4c-aee5-437c-b7fc-7b3c653e6ae6)

![Screenshot_2023-11-26-23-17-52-496_com.github.android.jpg](https://github.![Screenshot_2023-11-26-23-27-37-516_com.github.android.jpg](https://github.com/Krutoy242/Enigmatica2Expert-Extended/assets/936618/1c2fcc77-a6cd-4817-b631-04b3d7cf43c3)

41-397572927bc3)

![Uploading Screenshot_2023-11-26-23-27-37-516_com.github.android.jpg …]()

![Screenshot_2023-11-26-23-27-47-086_com.github.android.jpg](https://github.com/Krutoy242/Enigmatica2Expert-Extended/assets/936618/d8032564-06d3-4845-9dfc-7c138942f66a)

2023-11-27 23:12 UTC, TabakaSIM commented
> Did you tested if scythe will keep it's enchants or other nbt tags like Random Tweaker anchor on upgrading?

Fixed (Guess I fallen in love with deepUpdate from Zenscripts)


> Maybe I got this wrong, but, is scythe storing it's upgrades worth lore nbt? As I recall, Random Tweaker have special lore tags that could change lore of items. Did you test if it would exploit or destroy your nbt?

Honestly, I tried to use them, but haven't worked at all
 

 > It's squared distance, 7 blocks. Isn't it too small?

 It's actually normal distance (checked crafttweaker code). Sq stands for euclidean distance i guess

2023-11-28 07:48 UTC, Krutoy242 requested changes

2023-11-28 07:48 UTC, Krutoy242 commented on scripts/mods/thaumadditions.zs
> +    return item.updateTag({display:{Lore : lore}});
Are you sure this will not remove custom name from Scythe?

2023-11-28 07:48 UTC, Krutoy242 commented on scripts/do/mithminite_scythe.zs
> +        || entity instanceof IPlayer
Now this line is duplicated

2023-11-28 07:49 UTC, Krutoy242 commented
I pressed "Request Changes". Could you see comments now?

2023-11-28 08:14 UTC, TabakaSIM commented
Yes, now i can see them all

2023-11-29 08:40 UTC, merged